export { default as IconDashboard } from './icon-dashboard.tsx'
export { default as IconEye } from './icon-eye.tsx'
export { default as IconNonEye } from './icon-non-eye.tsx'
export { default as IconUser } from './icon-user.tsx'
export { SquareArrowLeftIcon } from './icon-chervon-left.tsx'
export { SquareArrowRightIcon } from './icon-chervon-right.tsx'
